### ISSUE TITLE
Need a better explanation of "adding", "committing" and "pushing" changes...

### ISSUE THREAD

**Issue by possibly** [ccsf2015-7/ccsf2015-7.github.io#4]
The current one is definitely wrong. If you need help formulating a better explanation, just ask for help!

**Comment by allan3723** [comment]
I'll take this

**Comment by paulproteus** [comment]
Awesome, @allan3723 ! Looking forward to seeing what you come up with.

**Comment by kayatoast** [comment]
I did work on this too.
